### ISSUE TITLE
AsyncAPI Schema object deserializer is missing some properties

### ISSUE THREAD

**Issue by crudbee** [LEGO/AsyncAPI.NET#122]
### Describe the bug
Schema deserializer `AsyncApiSchemaDeserializer.cs` is missing some fixed fields compared to the [AsyncAPI specification](https://www.asyncapi.com/docs/reference/specification/v2.0.0#schemaObject).

In particular:
```
patternProperties 
additionalItems 
propertyNames
```

### Additional context
Similar PR's touching the same code #120 and #121

**Comment by VisualBean** [comment]
`additionalItems` and `items` looks to be the same property, but according to spec 2.6 we should support both.
https://json-schema.org/understanding-json-schema/reference/array.html
https://www.asyncapi.com/docs/reference/specification/v2.6.0

It also looks like its another one of those 'bool' or 'object' types of things.
