### ISSUE TITLE
Project is targeting Net Core 

### ISSUE THREAD

**Issue by ByronMayne** [LEGO/AsyncAPI.NET#149]
### Describe the bug
The project currently targets .NetCore6 which is restricting where this library can be used.  In my case I wanted to use your library to write a source generator, however they are restricted to `NetStandard2.0`. Since this library does not actually need to be `NetCore` I think it would be better to switch it.

**Comment by VisualBean** [comment]
Closed as #150 was merged.
Its currently in the beta package, and will be released officially, soon.
@ByronMayne I would like the yaml support stuff to get into the next version as well, so i am holding out, with releasing till we get that in. 
How does that sound?

**Comment by ByronMayne** [comment]
That works for me. I can get to bring back the yaml changes and add a bunch more tests. The area I really want to have coverage is the datetime format stuff because it seems like it would be easy to break without knowing.
